---
apiVersion: v1
kind: Secret
metadata:
  namespace: isp-checker
  name: isp-checker-secrets-rw
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: VerySecurePassword

---
apiVersion: v1
kind: Secret
metadata:
  namespace: isp-checker
  name: isp-checker-secrets-ro
  labels:
    app.kubernetes.io/app: influxdb
    app.kubernetes.io/project: isp-checker
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_READ_USER: grafana
  INFLUXDB_READ_PASSWORD: VerySecurePassword

---
apiVersion: v1
kind: Secret
metadata:
  namespace: isp-checker
  name: influxdb-datasource-provisioner
  labels:
    app.kubernetes.io/app: grafana
    app.kubernetes.io/project: isp-checker
stringData:
  datasource.yaml: |-
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        orgId: 1
        url: http://influxdb-svc.isp-checker.svc.cluster.local:8086/
        user: grafana
        database: telegraf
        isDefault: true
        editable: true
