---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
    app.kubernetes.io/app: influxdb
    app.kubernetes.io/project: isp-checker
  name: influxdb-svc
  namespace: isp-checker
spec:
  clusterIP: 10.43.37.100
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  sessionAffinity: None
  type: ClusterIP
