---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: isp-checker-secrets-rw
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: VerySecurePassword

---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: isp-checker-secrets-ro
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_READ_USER: grafana
  INFLUXDB_READ_PASSWORD: VerySecurePassword

---
apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: grafana-datasource
stringData:
  datasource.yaml: |-
    datasources:
      - name: InfluxDB
        type: influxdb
        access: proxy
        orgId: 1
        url: http://influxdb-svc.monitoring.svc.cluster.local:8086/
        user: grafana
        database: telegraf
        isDefault: true
        editable: true
