name: Lint and validate
on: [ pull_request, push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.1.0
        with:
          dockerfile:  ./docker-compose/telegraf/Dockerfile
      - uses: actions/checkout@v2
      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v1.0.0
        with:
          file_or_dir: ./kubernetes/yaml/
          config_file: ./.yamllint
      - name: kube-score check
        uses: piraces/kube-score-ga@v0.1.1
        with:
          manifests-folders: "./kubernetes/yaml/*.yaml"
          ignore-exit-code: true
      - name: kubeval YAML validation
        uses: makocchi-git/actions-k8s-manifests-validate-kubeval@v1.0.1
        with:
          files: ./kubernetes/yaml/
          strict: true
          ignore_missing_schemas: true
          comment: true
          token: ${{ secrets.GH_TOKEN }}
